# Archivo YAML

map: 1

cantidad_de_worms: 5

worm:
  hp: 100
  speed: 2
  extra_hp: 25

turn_duration: 60
time_left_after_attack: 3

dynamite:
  damage: 50
  radius: 4

green_grenade:
  damage: 30
  radius: 2

bazooka:
  damage: 50
  radius: 2

banana:
  damage: 70
  radius: 4

holy_grenade:
  damage: 110
  radius: 8

air_strike:
  damage: 40
  radius: 2

armas:
  - codigo: 3
    nombre: Bazooka
    sprite_worm: /wbazlnk.png
    sprite_apuntado: /wbaz.png
    sprite_proyectil: /missile.png
    nombre: Bazooka
    descripcion: >
      Arma predilecta de los gusanos que dispara un misil que estalla al impactar con un tiro parabólico.
    mira: true
    combate_cuerpo_a_cuerpo: false
    disparo_potencia_variable: true
    cuenta_regresiva: false
    teledirigido: false
    trayectoria_afectada_por_viento: true
    municiones: infinitas
    danio:
      epicentro: 50 pts
      radio: 2 mts

  - nombre: Mortero
    descripcion: >
      Es igual a la bazooka pero al estallar lanza fragmentos al aire con trayectoria parabólica que estallan al impactar.
    mira: si
    combate_cuerpo_a_cuerpo: no
    disparo_potencia_variable: si
    cuenta_regresiva: no
    teledirigido: no
    trayectoria_afectada_por_viento: si
    municiones: 10
    danio:
      estallido_principal:
        epicentro: 50 pts
        radio: 2 mts
      fragmento:
        epicentro: 10 pts
        radio: 2 mts
    cantidad_fragmentos: 6

  - codigo: 2
    nombre: Granada Verde
    sprite_worm: /wgrnlnk.png
    sprite_apuntado: /wthrgrn.png
    sprite_proyectil: /grenade.png
    descripcion: >
      La segunda arma predilecta de los gusanos. Como otros tipos de granada no se ve afectada por el viento.
    mira: true
    combate_cuerpo_a_cuerpo: false
    disparo_potencia_variable: true
    cuenta_regresiva: true
    teledirigido: false
    trayectoria_afectada_por_viento: false
    municiones: infinitas
    danio:
      epicentro: 30 pts
      radio: 2 mts

  - nombre: Granada Roja
    descripcion: >
      Al igual que el Mortero, al explotar lanza fragmentos al aire con tiro parabólico que estallan al impacto.
    mira: true
    combate_cuerpo_a_cuerpo: false
    disparo_potencia_variable: true
    cuenta_regresiva: true
    teledirigido: false
    trayectoria_afectada_por_viento: false
    municiones: 10
    danio:
      estallido_principal:
        epicentro: 30 pts
        radio: 2 mts
      fragmento:
        epicentro: 10 pts
        radio: 2 mts
    cantidad_fragmentos: 6

  - codigo: 4
    nombre: Banana
    sprite_worm: /wbanlnk.png
    sprite_apuntado: /wthrban.png
    sprite_proyectil: /banana.png
    descripcion: >
      Es un tipo de granada que tiene la particularidad de rebotar varias veces de forma muy elástica hasta explotar.
    mira: true
    combate_cuerpo_a_cuerpo: false
    disparo_potencia_variable: true
    cuenta_regresiva: true
    teledirigido: false
    trayectoria_afectada_por_viento: false
    municiones: 5
    danio:
      epicentro: 70 pts
      radio: 4 mts

  - codigo: 5
    nombre: Granada Santa
    sprite_worm: /whgrlnk.png
    sprite_apuntado: /wthrhgr.png
    sprite_proyectil: /hgrenade.png
    descripcion: >
      Una de las armas más poderosas en el arsenal.
      Justo antes de estallar, produce un sonido característico.
    mira: true
    combate_cuerpo_a_cuerpo: false
    disparo_potencia_variable: true
    cuenta_regresiva: true
    teledirigido: false
    trayectoria_afectada_por_viento: false
    municiones: 2
    danio:
      epicentro: 110 pts
      radio: 8 mts

  - codigo: 6
    nombre: Dinamita
    sprite_worm: /wdynlnk.png
    sprite_proyectil: /dynamite.png
    descripcion: >
      Al activarse, el gusano deja en el lugar una dinamita que estalla luego de cierta cantidad de segundos.
    mira: false
    combate_cuerpo_a_cuerpo: true
    disparo_potencia_variable: false
    cuenta_regresiva: true
    teledirigido: false
    trayectoria_afectada_por_viento: false
    municiones: 5
    danio:
      epicentro: 50 pts
      radio: 4 mts

  - codigo: 1
    nombre: Bate de Baseball
    sprite_worm: /wbsblnk.png
    sprite_apuntado: /wbsbaim.png
    sprite_proyectil: /baseball.1.png
    descripcion: >
      Al activarse el arma, el gusano batea lanzando a todo aquel cercano. La dirección de los gusanos lanzados dependerá de la dirección del bateo.
    mira: true
    combate_cuerpo_a_cuerpo: true
    disparo_potencia_variable: false
    cuenta_regresiva: false
    teledirigido: false
    trayectoria_afectada_por_viento: false
    municiones: infinitas
    danio:
      epicentro: 10 pts

  - codigo: 8
    nombre: Ataque Aereo
    sprite_worm: /wairlnk.png
    sprite_proyectil: /airmisl.png
    descripcion: >
      Caen del cielo 6 misiles hacia el objetivo marcado por el jugador cada uno de ellos explotando independientemente. Los misiles pueden impactar antes si se encuentran en su trayectoria con algún otro objeto.
    mira: false
    combate_cuerpo_a_cuerpo: false
    disparo_potencia_variable: false
    cuenta_regresiva: false
    teledirigido: true
    trayectoria_afectada_por_viento: true
    municiones: 2
    danio:
      epicentro: 40 pts
      radio: 2 mts

  - codigo: 7
    nombre: Teletransportación
    sprite_worm: /wtellnk.png
    descripcion: >
      Al activarse la herramienta, el gusano puede teletransportarse a cualquier parte del escenario (salvo el interior de una viga).
    mira: false
    combate_cuerpo_a_cuerpo: false
    disparo_potencia_variable: false
    cuenta_regresiva: false
    teledirigido: true
    trayectoria_afectada_por_viento: false
    municiones: infinitas
    danio: ninguno
